---
site:
  title: "OpenShift Observability with OpenTelemetry"
  url: https://github.com/blues-man/openshift-observability-otel-lab
  start_page: openshift-observability-otel-lab::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./www
