---
site:
  title: "OpenShift Observability with OpenTelemetry"
  url: https://github.com/blues-man/openshift-observability-otel-lab
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./content/supplemental-ui

runtime:
  cache_dir: ./.cache/antora

output:
  dir: ./www
