app:
  enabled: true
  namespace: tutorial-application
  user: ""
  frontend:
    image: ghcr.io/pavolloffay/kubecon-eu-2026-opentelemetry-observability-on-budget-frontend:latest
    replicas: 1
  backend1:
    image: ghcr.io/pavolloffay/kubecon-eu-2026-opentelemetry-observability-on-budget-backend1:latest
    replicas: 1
  backend2:
    image: ghcr.io/pavolloffay/kubecon-eu-2026-opentelemetry-observability-on-budget-backend2:latest
    replicas: 1
  backend3:
    image: ghcr.io/pavolloffay/kubecon-eu-2026-opentelemetry-observability-on-budget-backend3:latest
    replicas: 1
  loadgen:
    enabled: true
    image: curlimages/curl:latest
  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.147.0
  userInfo:
    enabled: true
    title: "OpenShift Observability with OpenTelemetry"
deployer:
  domain: ""
