{{- if .Values.app.enabled }}
{{- if .Values.app.user }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.user }}-admin
  namespace: {{ .Values.app.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.app.user }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-k8sattributes-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-k8sattributes-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-k8sattributes-{{ .Values.app.namespace }}
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Values.app.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-tempo-write-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - tempo.grafana.com
    resources:
      - dev
    resourceNames:
      - traces
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-tempo-write-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-tempo-write-{{ .Values.app.namespace }}
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Values.app.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-loki-write-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - application
    resourceNames:
      - logs
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-loki-write-{{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-loki-write-{{ .Values.app.namespace }}
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Values.app.namespace }}
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  mode: deployment
  serviceAccount: otel-collector
  image: {{ .Values.app.collector.image }}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
    exporters:
      otlphttp/tempo:
        traces_endpoint: "https://tempo-simplest-gateway.{{ .Values.app.observabilityViewer.tempoNamespace | default "tempo-observability" }}.svc:8090/api/traces/v1/dev"
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        headers:
          Authorization: "Bearer ${file:/var/run/secrets/kubernetes.io/serviceaccount/token}"
      otlphttp/loki:
        logs_endpoint: "https://{{ .Values.app.observabilityViewer.lokiName | default "logging-loki" }}-gateway-http.{{ .Values.app.observabilityViewer.lokiNamespace | default "openshift-logging" }}.svc:8080/api/logs/v1/application"
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        headers:
          Authorization: "Bearer ${file:/var/run/secrets/kubernetes.io/serviceaccount/token}"
      debug:
        verbosity: basic
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/tempo, debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/loki, debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
{{- end }}
