{{- if .Values.app.enabled }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector.{{ .Values.app.namespace }}.svc:4318"
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector.{{ .Values.app.namespace }}.svc:4318"
{{- end }}
